<!doctype html>
<head>
  <script src="js/libs/modernizr-2.0.6.min.js"></script>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css') ?>
</head>

<body>

<div id="header"><!-- begin header -->
</div><!-- end header -->
<div class="menu">
<?php echo $this->navigation()->menu()->setMaxDepth(1); ?>
</div>
<div id="contentwrapper">
<div id="contentcolumn">
	<div class="box_center">
		<?php echo $this->layout()->content ?>
	</div>	
</div>
</div>

<div id="leftcolumn">
	<div class="box">
		<div class="box_title">leftmenu</div>
		dit is een testekeee
	</div>
</div>

<div id="footer2"><!-- begin footer -->
	MOLAS - ZEND EDITION v1
</div><!-- end footer -->

</body>
</html>